# Generated by Django 4.0.3 on 2022-04-11 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forTwi', '0002_fortwi_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fortwi',
            name='user',
        ),
    ]
