# Generated by Django 4.0.3 on 2022-04-10 18:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forYou', '0002_foryou_delete_fordb'),
    ]

    operations = [
        migrations.AddField(
            model_name='foryou',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='forYou', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
