# Generated by Django 4.0.3 on 2022-04-11 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forYou', '0003_foryou_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foryou',
            name='user',
        ),
    ]
