# Generated by Django 4.0.3 on 2022-04-11 07:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forYou', '0005_foryou_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foryou',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fory', to=settings.AUTH_USER_MODEL),
        ),
    ]
